version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: hypothesis
    versions:
    - 6.1.0
    - 6.1.1
    - 6.10.0
    - 6.2.0
    - 6.3.0
    - 6.3.1
    - 6.3.2
    - 6.3.3
    - 6.3.4
    - 6.4.0
    - 6.4.2
    - 6.4.3
    - 6.6.0
    - 6.7.0
    - 6.8.0
    - 6.8.1
    - 6.8.3
    - 6.8.4
    - 6.8.5
    - 6.8.8
    - 6.8.9
    - 6.9.1
    - 6.9.2
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: twine
    versions:
    - 3.3.0
    - 3.4.0
  - dependency-name: tox
    versions:
    - 3.21.3
    - 3.21.4
    - 3.22.0
  - dependency-name: pip
    versions:
    - "21.0"
    - 21.0.1
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pytest-mock
    versions:
    - 3.5.1
