sudo: false

language: python

matrix:
    include:
      - python: 3.5
        env: TOXENV=py35
      - python: 3.6
        env: TOXENV=py36
      - python: pypy3.5
        env: TOXENV=pypy3
      - python: 3.5
        env: TOXENV=flake8

script: tox

install:
- pip install tox
